### ISSUE TITLE
Unicode support 

### ISSUE THREAD

**Issue by yipihey** [tmlbl/AppConf.jl#6]
In order to allow unicode variables to be used I had to change 
the findeq function in AppConf.jl by a minor amount.

We just use the chr2ind() function to make sure the index we use corresponds to
the position i the unicode string. 
Like so:

function findeq(ln::AbstractString)
    for i = 1:length(ln)
        c = chr2ind(ln, i);
        if ln[c] == '='
            return c
        end
    end
    return -1
end

This way parameters such as
γ= 1.66667

now also work.

From my testing so far this seems to work well .

**Comment by tmlbl** [comment]
Great! Are you able to make a pull request?

**Comment by yipihey** [comment]
Thanks. Yes. I submitted the pull request. Can you check whether this works for you?
